const Classic = {
  name: 'Everyone',
  title: 'Best Truth or Dares for',
  description: ` classic game of truth or dare is the perfect way to get to know your besties even better. We rounded up the very best truth or dare questions (and dares) that will keep things interesting. Whether you're at a slumber party with BFFs or an afternoon hang with new friends, this game is a go-to that provides endless entertainment—no consoles or playing cards required. There's a little bit of everything, including funny truth questions to prompt embarrassing stories and wacky dares that'll take you (a little) out of your comfort zone.`,
  content: {
    truth: [
      'Who is your favorite family member?',
      'What is your least favorite part about family gatherings?',
      'What is the biggest secret that you kept from your parents when you were growing up?',
      'What is your favorite movie that you secretly know is actually terrible?',
      'What is your worst habit?',
      'Have you ever bribed or flirted with a police officer to get out of a ticket?',
      'What is something you most look forward to doing when you retire?',
      'Do you have a bucket list? If so, what is one thing on that list?',
      'What is one thing you are always losing?',
      'What is the strangest thing you have ever bought?',
      'Do you have a weird collection? If so, what?',
      'Tell us about the last dream you can remember. Don’t leave any details out!',
      'Have you ever shared chewing gum with anyone?',
      'Have you ever lied about being sick so you could stay home from work or school?',
      'If you could do one thing you did when you were a child, what would it be?',
      'Have you ever danced on a table when you were drunk?',
      'Have you ever told someone you wouldn’t be home just so they wouldn’t come over to yours?',
      'What is the one thing you dislike about yourself?',
      'What is the one thing you really like about yourself?',
      'What is the one thing you would stand in line for?',
      'Have you ever lied on your resume to get a job?',
      'If anyone in your family could win an award for being the most annoying, who would it be?',
      'What is the most embarrassing thing that has happened to you in front of a crowd?',
      'What is your least favorite household chore?',
      'If you could hire someone to do one thing for you, what would it be?',
      'What was the most embarrassing thing that you ever did while on a date?',
      'What was the worst gift you ever received?',
      'What is the one thing you are the most afraid of?',
      'Have you ever sent an inappropriate text to your mom or dad by accident?',
      'Have you ever bought something to wear to an event and then returned it to the store when the event was over?',
      'Have you ever fallen asleep in church?',
      'Did you ever break up with someone just before a public holiday so that you didn’t have to buy them a gift?',
      'Have you ever kept a library book?',
      'Have you ever cheated on a test?',
      'If you could create your own job title, what would it be?',
      'What is your excuse to get out of exercising?',
      'What was the one thing you could never learn how to do no matter how hard you tried?',
      'What was your favorite childhood television show?',
      'Did you ever sneak into an adult movie when you were underage?',
      'If you had a remote control that would operate anything, what would you control?',
      'Have you ever complained about something at a restaurant just to get out of paying?',
      'What is one thing you did as a child that you still enjoy?',
      'Do you prefer the big city or country life?',
      'What is your guilty pleasure?',
      'What are your favorite pizza toppings?',
      'Where is your favorite vacation spot?',
      'Have you ever used a work computer for personal use?',
      'What is your favorite thing to do with your leisure time?',
      'What was the worst vacation you ever had?',
      'If you were to bury a time capsule, what is one thing you would put in it?',
      'If you were granted three wishes, what would they be?',
      'What is your favorite holiday?',
      'What is your biggest pet peeve?',
      'If you could choose a different career, what would it be and why?',
      'If you could live anywhere in the world, where would it be?',
      'What is your favorite snack from a vending machine?',
      'Have you ever forgotten a special person’s birthday?',
      'Have you ever taken a drink straight out of the carton?',
      'On a scale from 1-10, where does your patience fall?',
      'If animals could talk, which one would you have a conversation with?',
      'Tell us about the worst restaurant experience you ever had.',
      'Is there any movie that always makes you cry?',
      'Say the funniest joke you’ve ever heard.',
      'What is something you find absolutely disgusting to the point you get sick?',
      'Have you ever been stuck in an elevator and if so who were you with?',
      'Who was your favorite teacher in school?',
      'What was your favorite subject in school?',
      'What is something that you are not looking forward to?',
      'Knowing now what you didn’t know then, what would you have done differently?',
      'Have you ever told a secret after you were told not to?',
      'Are you always on time, or are you always late?',
      'Are you a morning person or a night person?',
      'What is one job you would never want to do?',
      'What is your favorite ice cream flavor?',
      'When you think that no one is listening, do you sing in the shower?',
      'The last time you argued with someone, did you apologize first or was it the other person?',
      'What is the best gift you ever received?',
      'Is there any food that you can never eat?',
      'What was your favorite childhood toy?',
      'If you were given a million dollars, what would you do with it?',
      'Have you ever been arrested?',
      'What is your favorite sport?',
      'What is your favorite ride at the amusement park?',
      'Do you prefer the beach or the mountains?',
      'Have you ever been on a train?',
      'If you found a large amount of money, would you keep it or would you try to find the owner?',
      'What is the angriest you’ve ever been?',
      'What makes you the happiest?',
      'What is your favorite sandwich?',
      'Is there anything you regret buying, and if so, what is it?',
      'What is the best thing you ever bought?',
      'If you were invisible what is something you would do?',
      'What makes you feel uncomfortable?',
      'Do you prefer cats, dogs, or neither?',
      'If there was one thing you could change about yourself, what would it be?',
      'If you were a giant, what would you like to do?',
      'What is your favorite music genre?',
      'Have you ever blamed your sibling for something you did just so that you wouldn’t get in trouble?',
      'How old were you when you got your first cell phone?',
      'When is the last time you took a shower?',
      'When is the last time you brushed your teeth?',
      'Describe your favorite activity when you’re alone.',
      'What do you like to do when you are with your friends?',
      'Who was your first crush?',
      'How old were you when you had your first crush?',
      'What is the best time of day for you?',
      'What is your least favorite time of the day?',
      'If you didn’t have to work, what would you do with all your time?',
      'Tell us about your favorite possession.',
      'Name the three websites you visit the most.',
      'What was the best day you ever had?',
      'Describe the worst day you’ve ever had.',
      'Say your biggest fear in life.',
      'Did you have a nickname as a child and if so, what was it?',
      'Do you prefer mushy movies or funny ones?',
      'If you only had two minutes to get out of your house, what would you grab?',
      'What is your favorite vegetable?',
      'What is your favorite fruit?',
      'Do you have a special talent and if so, what is it?',
      'Have you ever been married?',
      'What do you like to put on your toast?',
      'What is the spiciest thing you’ve ever eaten?',
      'If you could live anywhere in the world, where would it be?',
      'Do you prefer Facebook or Twitter?',
      'What season is your favorite?',
      'Who is your most annoying neighbor?',
      'If you could be someone else for a day who would you be?',
      'What was the name of the street you grew up on?',
      'Which do you like better, cars or trucks?',
      'What is your favorite outdoor pastime?',
      'Which do you like better, Coca-Cola or Pepsi?',
      'What is your favorite month and why?',
      'Do you like to read and if so, what is your favorite book?',
      'Have you ever met a celebrity, if so, who?',
      'Has there have been a time when you cheated to win a game?',
      'Have you ever sent a love message to your boss by accident that was meant for someone else?',
      'What food do you absolutely despise?',
      'Who is the person you are the most jealous of and why?',
      'How many different languages can you speak and what are they?',
      'Do you have any tattoos and if so, where?',
      'Have you ever been outside of the country?',
      'What is one thing your grandparents taught you how to do?',
      'Have you ever been to the opera?',
      'Do you prefer talking or texting?',
      'Have you ever had an argument with someone through text?',
      'What was the last thing you ate?',
      'Have you ever been to the zoo?',
      'What is the grossest thing you’ve ever eaten?',
      'What is your most regrettable kiss?',
      'Have you ever failed a test? What was it?',
      'Who is your favorite teacher and why?',
      'Who was your longest secret crush?',
      'Where do you like to go when you’re feeling down?',
      'What is your favorite song?',
      'What is something you have never told anyone in this room?',
      'What do you like to wear when no one is around?',
      'Who would rather be stuck on a desert island: the person on your left or on your right?',
      'For parents: which is your favorite child? For children: which is your favorite parent?',
      'Have you ever shoplifted or stolen anything?',
      'Describe the worst date you’ve ever been on.',
      'If you could be fluent in one of these languages which would it be: Chinese, French or Russian?',
    ],
    dare: [
      'Completely cover yourself in toilet paper to look like a mummy.',
      'Randomly call a person from your phone and sing them a song.',
      'Call a family member of someone in the room and explain why you love your friend so much.',
      'Run outside and shout as loud as you can, “I am the best person in the world!”',
      'Mix all the sauces you have in your fridge and drink up.',
      'Prank call a friend’s partner.',
      'Call up a pizza place and order Chinese food.',
      'Take a shower without removing any of your clothes.',
      'Cover up your eyes (or wear a blindfold), and walk around the room for two minutes without watching where you’re going.',
      'Impersonate someone in the room and people have to guess who it is.',
      'Improvise and perform a two-minute comedy routine in front of everyone.',
      'Act like a dog for two minutes without laughing.',
      'Pour a freezing cold glass of water over your face without reacting.',
      'Talk about something you regret in your life.',
      'Tell a stranger walking past that you love them.',
      'Put as many pieces of cheese puffs in your mouth at one time as you can.',
      'Screenshot a picture of your browser history and send it to a random person in your contacts.',
      'Log into Facebook and like every picture for the past year of the first person you see.',
      'Rip off a piece of paper and eat it.',
      'Cover your hair with milk and don’t wash off until the end of the game.',
      'Text your mom the last picture saved on your phone.',
      'Pretend to be a chicken for 30 seconds.',
      'Stand up and run on the spot as fast as you can until it’s your turn.',
      'Sniff the player to your right’s armpit.',
      'Allow another player to throw flour in your face.',
      'Allow a random player to tickle you for 30 seconds.',
      'Go into the kitchen and take a bite out of something in the trash.',
      'Spritz perfume into your mouth.',
      'Head outside and lick a car tire.',
      'Take a picture of yourself pulling a funny face and set it as your Facebook profile picture for the rest of the day and night.',
      'Pass your phone to the person to your right and allow them to put any status on one of your social media accounts.',
      'Let someone in the group give you a wedgie.',
      'Grab a random object in the room and try and sell it to the group for two minutes.',
      'Kiss the second person to your left on the lips.',
      'Sing the chorus from a random song with all your heart.',
      'Speak in a baby’s voice for the next five things you have to say.',
      'Give someone in the group all the money you have in your purse.',
      'Take someone’s socks off and wear them like gloves for three minutes.',
      'Slap yourself in the face any time someone says “and” in the next three minutes.',
      'Blindfold yourself and let someone in the group feed you something of their choosing.',
      'Knock on your neighbor’s door and tell them how grateful they should be to live next to someone so awesome.',
      'Try to lick your elbow for the next three minutes.',
      'Laugh out loud at everything the person to your left says until it’s your turn.',
      'Stand up and try to break dance.',
      'Try to impersonate your favorite singer for one minute.',
      'Pick out the best and worst dressed individuals in the group.',
      'Act like you’re drunk for next three minutes.',
      'Hum a random song and you can’t stop until someone guesses what it is.',
      'Let someone bite your finger until it hurts.',
      'Attempt to keep your eyes as wind open as possible without blinking for next three minutes.',
      'Open a book, newspaper or magazine, and sing two random sentences as best you can.',
      'Show everyone the four most recent pictures on your phone.',
      'Write and perform a song that is at least two minutes long.',
      'Ring a random person from your phone and confess that you’re in love with a fictional character.',
      'Hold your breath for as long as you can.',
      'Apply makeup without looking in the mirror.',
      'Let a player write something on your head and don’t wipe it off until the end of the game.',
      'Do as many sit-ups as you can in one minute.',
      'Trade one item of clothing with another player and wear for the rest of the game.',
      'Try to sing a song with your mouth full of a drink.',
      'Eat a spoonful of a spicy sauce.',
      'Hold mouthwash in your mouth for as long as possible.',
      'Allow the second player to your right to make an alcoholic drink and you have to drink it as fast as you can.',
      'Completely shave off one of your eyebrows.',
      'Let someone wax half of your leg.',
      'Nibble at another player’s fingernails.',
      'Go outside and ask a stranger to smell your breath.',
      'Eat an entire onion without crying.',
      'Allow another player to cut a small chunk out of your hair.',
      'Massage another player’s back for five minutes.',
      'Sit among other players wearing only your underwear.',
      'Let another player keep any item of clothing from your wardrobe.',
      'Try to juggle with three eggs.',
      'Spank the person to your right.',
      'Confess your undying love to another player in the room.',
      'Blindfold yourself and allow another player to feed you something of their choosing, and you’ve got to guess what it is.',
      'Smell someone else’s shoes for 5 seconds.',
      'Text the last person you called saying, “I love you”.',
      'Speak in an accent chosen by another player for the rest of the game.',
      'Streak around the room for 10 seconds.',
      'Sit on someone else’s lap for a minutes.',
      'Allow another player to search anything they want on your phone.',
      'Eat an item of food off of someone’s face without using any hands.',
      'Passionately kiss the back of your hand and let someone record it.',
      'Describe someone else in the group and others have to guess who it is.',
      'Tell everyone about an embarrassing crush you once had.',
      'Grab a broom and pole dance for next 2 minutes.',
      'Whisper a secret about yourself to another player in the group.',
      'Perform your best air guitar routine without any music playing.',
      'Twerk wearing only your underwear.',
      'Let another player crack an egg on your head.',
      'Dress up like the opposite sex and let another player take a picture and upload it online.',
      'Put an ice cube down your pants and let it melt.',
      'Pretend that you’re a cat and rub up against the other players for one minute.',
      'Say the entire alphabet backward.',
      'Go to a neighbor’s house and ask if they have any spare food because you’re hungry.',
      'Make up a two-minute rap about an inanimate object in the room.',
      'Call the tenth contact on your phone and tell them all about your day, for no apparent reason.',
      'Head outside and talk to a random stranger as if they’re an old friend you haven’t seen in years.',
      'Balance an object on your head while walking around the room for one minute.',
      'Let the player to your left give you a new hairstyle for the rest of the game.',
      'Tell everyone an embarrassing story about yourself.',
      'Take a mouthful of water and tell a funny story about something that’s recently happened to you.',
      'Get down on one knee and pretend to propose to another player.',
      'Sing everything you want to say for the next 2 minutes.',
      'Eat as many pieces of bread as you can in two minutes.',
      'Lick a bar of soap from the bathroom.',
      'Text your mom that you’re going to be a dad.',
      'Text your mom and tell them you’re pregnant.',
      'Go outside and carry a sign that says “kiss me if you think I’m attractive”.',
      'Take a bite and swallow a piece of a banana skin.',
      'Lick an animal’s fur.',
      'Pretend that you’re a sheep for no reason whatsoever.',
      'Write a poem about why you are the best person in the world.',
      'Take a selfie with some old trash.',
      'Spank the closest person to you.',
      'Prank call your ex and tell them that you want to get back together.',
      'Eat a sandwich filled with ingredients chosen by other players.',
      'Put a teaspoon of salt in your mouth.',
      'Consume as many chilies as you can in two minutes.',
      'Head outside for a walk and talk aloud to yourself.',
      'Tell a stranger that you’re having a bad day and need someone to talk to.',
      'Lick the floor.',
      'Go outside and wink at the first person you see.',
      'Dance outside for two minutes without any music playing.',
      'Tell everyone about a celebrity crush you have.',
      'Take a picture of yourself pulling a funny pose and upload it to social media.',
      'Call a random person and wish them a happy birthday.',
      'Have a conversation with the TV.',
      'Act like you’re a child for two minutes.',
      'Drink an entire bottle of milk to yourself.',
      'Laugh like a hyena to everything everyone says until it’s your turn.',
      'Prank call a car breakdown company and say that you’re sad because you don’t have a car.',
      'Send a direct message to the last person you wrote to on Instagram saying that they’re beautiful.',
      'Give a stranger five dollars.',
      'Wash another player’s feet.',
      'Dip your hand in toilet water.',
      'Apply lipstick to your mouth and teeth and walk outside.',
      'Do a handstand with your feet against the wall and hold for 30 seconds.',
      'Give your phone to the person on your left and let them send any message they want to anybody on your contact list.',
      'Let the person to your right give you a temporary marker tattoo on your forehead of anything they want.',
      'Call your sibling or cousin and speak to them for one minute entirely in an Italian accent.',
      'Do the entire Gangnam Style dance using headphones so no one else hears the song.',
      'Sing your country’s national anthem while plugging your nose.',
      'Choose one other player and dance to the Titanic theme song while holding an orange between you (no hands). Don’t let the orange fall!',
      'Call your neighbor and make monkey sounds for 30 seconds straight.',
      'Make a love declaration to the player sitting opposite you.',
      'Do a belly dance to the tune of Ricky Martin’s “La Voda Loca”',
      'Email your favorite teacher and tell them you love them.',
      'Propose to the last person you sent a text message to.',
    ],
  },
};

export default Classic;
