const CoupleNormal = {
  name: 'Couples',
  title: 'Best Truth or Dares for',
  description: `Truth or Dare is one game you should play for couples to know more about each other and have fun too. This will encourage your partner to tell you more about themselves and vice versa. We have come up with a long list of truth or dare questions for couples. You may use these fun questions for couples, whether to ask in a couples’s party or in solitude with your partner`,
  content: {
    truth: [
      'Did you ever fart inside an elevator?',
      'Did you ever pick your nose in office?',
      'Which is your favorite song to hum in the shower?',
      'Your worst addiction?',
      'Have you ever peed while playing on the beach?',
      'Have you ever lied to your partner?',
      'Narrate your first breakup story giving all details.',
      'What’s your biggest turn off in a person of the opposite sex?',
      'What turns you on?',
      'How far did you go on your first date?',
      'Did you ever taste your pet’s food?',
      'Ever used a cheesy pickup line on your fitness trainer?',
      'Have you ever cursed your partner’s family?',
      'What is the craziest thing on your bucket list?',
      'Which part of your body gets the most compliments? And by whom?',
      'Which actor would you swap your life with for 10 days?',
      'Describe your idea of a horrible date.',
      'Who was your crush in school?',
      'What makes you cry and jump in joy at the same time?',
      'Did you ever have a crush on a high school teacher?',
      'Do you like your partner’s cooking?',
      'Beaches or mountains?',
      'Did you ever dance intimately with someone?',
      'What is the worst gift you have ever received from your partner?',
      'How many kids are you planning to have?',
      'What, in your opinion, is something I must change about myself?',
      'What is your biggest fear about relationships?',
      'What were your exact thoughts while saying, “I do” ?',
      'What is one of the most terrific things that we did together?',
      'Rate our love story on a scale of 1 to 10?',
      'What is your favorite thing to do together?',
      'Are you possessive about me or our relationship?',
      'Partying at a club or a movie night at home?',
      'What is your idea of a perfect couples’ holiday?',
      'What is your favorite time of the year?',
      'Would you ever want to undergo plastic surgery? Why?',
      'What is the biggest insecurity about our relationship?',
      'How would you spend an entire week without me?',
      'Which is your favorite color on me?',
      'What would you enjoy about being stranded with me on a deserted island?',
      'Did you ever two-time while being in a committed relationship?',
      'Have you ever tried skinny dipping in a public pool?',
      'Do you have the hots for someone at your workplace?',
      'At which age did you have your first kiss and with whom?',
      'Did you ever make out in a public library?',
      'Did you ever stalk your ex?',
      'Do you prefer a masseuse of the opposite gender or the same?',
      'Tell something you were always afraid to express.',
      'Will you allow me to check the browsing history on your mobile?',
      'Ever dated someone older than you?',
      'Were you ever attracted to someone from the same gender?',
      'Have you ever had a crush on your best friend’s spouse?',
      'Have you ever burped while kissing someone?',
      'Who is hotter? Me or you?',
      'Did you ever accidentally send a wrong intimate message to your colleague?',
      'Did you ever break up with an ex right before their birthday to avoid buying them a birthday gift?',
      'Did you ever start a rumor about someone you hate?',
      'Did you ever visit a strip club?',
      'If you could win a thousand dollars, would you give up watching your favorite Netflix series?',
      'Did you, at any time, feel uncomfortable in the presence of your parents? When?',
      'Did someone ever break your heart? Who? (I’ll break their bones)',
      'Is there something that you love a lot, but you sacrificed just for me?',
      'Do you have a favorite in-law? Who is he/she?',
      'What is one thing that makes you regret our relationship?',
      'What am I worth exchanging with?',
      'What is one household chore that you hate to do?',
      'Did you ever lie about your GPA?',
      'How many serious relationships have you had?',
      'Did you ever have a tinder profile?',
      'Were you ever on a blind date?',
      'Which animal comes to your mind when you think of me?',
      'Is there a nickname I gave, which you absolutely hate?',
      'Rate the style of my dressing on a scale of 1 to 10.',
      'Name one thing that you just can’t give up even for me.',
      'Do you believe in love at first sight?',
      'Do you prefer a masseuse of the opposite gender or the same?',
      'Will you allow me to check the browsing history on your mobile?',
      'Ever dated someone older than you?',
      'What is your idea of a perfect marriage?',
      'Does the scent of my perfume arouse you?',
      'Share one thing which you think could cause our break up.',
      'Which of my friends do you like to talk to and whom do you hate?',
      'What was the first ever lie you told me?',
      'When you suddenly hear my name in public, what is that one thing which comes to your mind?',
      'What could be your alternate career?',
      'Do you like giving or receiving a lap dance?',
      'Have you ever sent an inappropriate selfie to your ex?',
      'Describe your favorite clothing style.',
      'What kind of food turns you on?',
      'Describe your first intimate experience.',
      'What is that one change you have noticed after marriage?',
      'What is one thing about our physical intimacy that you miss when I’m not around?',
      'Did you ever share a chewing gum with someone?',
      'Do you enjoy PDA?',
      'Which is the most embarrassing show you are guilty of watching?',
      'Did you ever get involved in doing something illegal?',
      'Name two of your guilty pleasures.',
      'What is something disgusting, but you still like doing?',
      'Fierce or fiesty, what defines you in bed?',
      'Would you mind satisfying somebody for money?',
      'How perfect am I as your partner?',
      'When was the longest time you have stayed in a bathroom and why?',
    ],
    dare: [
      'Brush your teeth with apple cider vinegar.',
      'Dip a marshmallow in soya sauce and eat it.',
      'Open the backyard door and bark like a dog for 30 seconds.',
      'Open your Instagram or Facebook and like each post of your ex.',
      'Call an Italian restaurant and order sushi.',
      'For the next 5 minutes, talk only in a whispering tone.',
      'Slowly eat a spoonful of cinnamon powder.',
      'Use toothpaste to wash your hands.',
      'Call your colleague and yell liar in the phone, three times.',
      'Pretend you have won a Grammy and give an acceptance speech.',
      'Lick your dog’s ear.',
      'Read the newspaper in a romantic style.',
      'Call up pizza guys and ask if they have formula milk.',
      'Call your best friend and ask if he/she has stolen your watch.',
      'Jump like a frog for 2 minutes.',
      'Re-enact your favorite romantic scene.',
      'Without using any music, sing and dance to any beat.',
      'Sit like a chair against a wall for 2 minutes.',
      'Using cloves of garlic apply a lip balm or a lipstick.',
      'Pretend the mop is your guitar, give a stage show performance.',
      'Call an old friend and talk gibberish.',
      'For a minute, pretend to walk on a ramp and pout for cameras.',
      'Eat a cookie without using your hands.',
      'Mix peanut butter with chili sauce spread it on a slice of bread and eat it.',
      'In the living room, land your imaginary spacecraft and talk like an alien.',
      'Go shirtless and pound like a gorilla on your chest, for one whole minute.',
      'Talk to Siri for a minute without any interruption.',
      'Sing a lullaby beatboxing.',
      'Impersonate your favorite in-law.',
      'Eat like a monkey for a minute.',
      'Eat 10 cookies in one minute.',
      'Record a video of you eating Chinese with chopsticks and share it with your friends.',
      'Close your eyes and floss the teeth.',
      'Whisper one of your darkest secrets.',
      'Play a baby crying video on YouTube and dirty dance on the music of it, till the end of the video.',
      'Open and shut the fridge 16 times, in 16 stylish ways.',
      'Doodle the best possible image of your boss and post it on Twitter without giving any other details.',
      'Eat a bowl of spaghetti using your fingers.',
      'Change your Facebook profile photo to an ugly selfie.',
      'Take a screenshot of your browsing history, print it and paste it on the bathroom mirror.',
      'Change the status of your Facebook profile to “feeling sad”.',
      'Make an account on a dating app and write a crazy bio.',
      'Write a 10-line naughty story and share it with your friends on the Whatsapp group.',
      'Send a weird GIF to the 10th person on your contacts list.',
      'Imitate any five emojis.',
      'Perform a stand-up comedy.',
      'Act like a crying toddler for 4 minutes.',
      'Place ice cubes on your palm and close your fist. Hold it till they all melt.',
      'Cut a few onions and narrate a funny story while cutting them.',
      'Strike up a funny conversation with your parents and hang up abruptly.',
      'Dance with your dog for 3 minutes.',
      'Dig into the trash can and name any three things you have picked.',
      'Text a poor joke to your parents.',
      'Use a voice changing filter and send a funny voice message to your ex.',
      'Talk to a chair as if it’s your celebrity crush.',
      'Row an imaginary boat for one minute.',
      'Reveal what is inside your bag. Every small detail.',
      'Tell 5 of your favorite quotes in one single breath.',
      'Juggle 3 eggs without breaking them.',
      'Dress up like a pop star and sing a romantic song dedicated to our relationship.',
      'Get down on one knee and propose to me.',
      'Say I love you while doing 20 jumping jacks.',
      'Cook a delicious meal in less than 40 minutes.',
      'Plank for 30 seconds and while doing it say one thing you love about me.',
      'Stuff your mouth with marshmallows(or anything) and describe why you love me.',
      'Blindfold and make me a sandwich.',
      'Freestyle rap about our relationship.',
      'Stand on one leg and say any two things that you hate about our relationship.',
      'Go live on any social media account and declare your love for me.',
      'Give me a relaxing foot massage.',
      'Express your love in sign language.',
      'Write a short poem about our love story and sing it.',
      'Do the best couple yoga pose.',
      'Recreate the wedding photos.',
      'Do the laundry for entire next week.',
      'Give me a piggyback ride for 1 whole minute.',
      'Do 5 squats in the slowest manner possible.',
      'Wear your dress inside for next 5 minutes.',
      'Narrate a fake romantic and intimate story about a date with your celebrity crush.',
      'Twerk at a boring song, till the music stops.',
      'Dance on an imaginary pole.',
      'Unwrap a candy with just your teeth.',
      'Belly dance with something from the kitchen as a prop.',
      'Allow being tickled when you are blindfolded.',
      'Draw the alphabet in the air with your lips.',
      'Send a dirty text using only emojis to your best friend.',
      'Eat a cup cake in the nastiest way possible.',
      'Cross-dress and click 10 pictures. Share the pictures with your best friends.',
      'Prank call an ex and say something dirty.',
      'Hug and kiss a cushion or a pillow.',
      'Vacuum the house wearing only pajamas.',
      'Spank yourself 5 times.',
    ],
  },
};

export default CoupleNormal;
