const CoupleDirty = {
  name: 'Couples',
  title: 'Top Dirty Truth or Dares for',
  description: `Relationships can sometimes get dry and boring. It reaches that point in life when you have done almost everything there is for fun and new fanciful ideas are hard to come by.<p> Well, have you tried with question games like the sexual dirty truth or dare questions with your friends? Dirty truth or dare questions is a good game for you to play with people close to your heart or life when you feel you have exhausted all the fun in the world. If you are looking for hot questions to stimulate conversations in your upcoming party or sizzling questions for your sleepover, this list of unique dirty truth or dare questions will be ideal for you.</p>`,
  content: {
    truth: [
      'Where is the craziest place you’ve ever had sex?',
      'Who was the worst you’ve ever had and the best you’ve ever had?',
      'Read me your best sexting line in a sexy accent.',
      'What’s the kinkiest thing you’ve ever done in bed?',
      'What’s the most adventurous thing you want to try in bed?',
      'How old were you when you lost your virginity and how did it go?',
      'Who was your first kiss?',
      'What’s a popular fetish that you would never want to try?',
      'Do you remember the first time you experienced an orgasm? Tell me about it.',
      'What’s your favorite body part on your body?',
      'If you could have one sexual superpower, what would it be?',
      'Have you ever been tempted to cheat on your significant other?',
      'What’s your favorite position?',
      'What position is popular that you think is overrated?',
      'Do you think virginity is special?',
      'What do you wish you had learned about sex way earlier than you did?',
      'Would you rather be the person doing the spanking or be spanked yourself?',
      'What’s something I do that unintentionally turns you on a lot?',
      'What’s something I do in bed that turns you on a lot?',
      'What’s something in bed that you would like me to try?',
      'What’s a position you want to try?',
      'Do you have anything you fear sexually?',
      'How often do you pleasure yourself a week?',
      'Have you ever watched porn? What’s your go-to category?',
      'Where is the craziest place you’ve ever masturbated?',
      'What’s an odd fetish that you would try out?',
      'What’s the record amount of times you’ve had sex in one day?',
      'Have you ever had sex while other people were in the room without them knowing?',
      'Are you a fan of foreplay?',
      'Are you a fan of shower sex?',
      'When’s the last time you pleasured yourself?',
      'Do you enjoy receiving nudes?',
      'Have you ever been to a strip club? If not, would you like to go?',
      'Have you ever wanted to try role play?',
      'Have you ever masturbated with something weird?',
      'How old were you when you first watched porn?',
      'Have you ever wanted to try bondage?',
      'Have you ever received a lap dance?',
      'What’s your favorite fantasy to pleasure yourself to?',
      'What sex act have you done that you never want to do again?',
      'Have you ever faked an orgasm with me?',
      'Tell me about the best orgasm you’ve ever had.',
      'Have you ever had a crazy one-night stand? Tell me about it.',
      'If you woke up as the opposite sex, what’s the first thing you would explore about yourself.',
      'Do you like listening to music while having sex?',
      'What’s the longest you’ve gone without having sex?',
      'What’s something sexy I say that you love?',
      'Have you ever thought about experimenting with someone of the same sex?',
      'Have you ever watched or wanted to watch another couple have sex?',
      'Lights off or lights on during sex?',
      'Where is your favorite place to have sex?',
      'Does dirty talk get you horny?',
      'Would you rather give or receive pleasure?',
      'What’s a sexual act that you never want to try?',
      'What’s the dirtiest thing you’ve ever been caught doing or almost been caught doing?',
      'What’s something you’ve fantasized about your partner that’s made you finish when pleasuring yourself before?',
      'Do you like sex to be rough or sensual?',
      'Have you ever been friend-zoned?',
      'Have you ever paid for porn or sexual pleasure in any way?',
      'What’s the quickest way to get you into bed?',
      'Do you prefer a little hair or smooth-shaven down there?',
      'What’s the least sexual thing your partner has done that’s gotten you aroused somehow?',
      'Describe to me in detail your sexiest pair of underwear.',
      'What was your first impression of me?',
      'When did you have your first sexual feelings?',
      'When was your first sexual experience?',
      'What was your craziest sexual experience like?',
      'Where is your favorite place to be kissed on your body?',
      'What’s the dirtiest thought you’ve ever had?',
      'What’s the dirtiest dream you’ve ever had?',
      'Where’s the raunchiest place you dream of having sex?',
      'Describe to me the best sex you’ve ever had.',
      'Have you ever had phone sex before?',
      'Who’s the one that got away?',
      'Are you turned on right now?',
      'Have you ever been tied up before?',
      'What is something that is completely off-limits from trying in bed?',
      'If you were to give a full body massage, where would you start and end?',
      'What was your funniest sexual experience like?',
      'Have you ever had sex in public? Would you or would you again?',
      'What celebrity would you have sex with if you could?',
      'How can I get you horny?',
      'Have you ever done something that you feel guilty about?',
      'What was your biggest sexual disappointment?',
      'Have you ever been sexually rejected?',
      'Describe the funniest mistake that’s happened to you while having sex.',
      'Do you have a name for your penis or vagina?',
      'What kinds of sex toys would you want to try?',
      'Have you ever kissed someone of the same gender?',
      'Have you ever flashed someone?',
      'Do you like sexting?',
      'Have you ever thought about me naked while talking to me?',
      'What automatically makes you orgasm during sex?',
      'Have you ever had or fantasized about an orgy?',
      'Have you ever had or fantasized about a threesome?',
      'Have you ever taken someone’s virginity?',
      'What excites you the most in bed?',
      'Have you ever masturbated in public?',
      'What’s your wildest sexual fantasy?',
      'What dirty secrets are you hiding?',
      'Have you ever tried anal sex?',
      'Do you like anal?',
      'Have you ever done something sexy with food during sex or foreplay?',
      'Describe what it was like the first time someone went down on you.',
      'Have you ever touched yourself while having sex?',
      'What’s the worst kiss you’ve ever had and why?',
      'What’s the best kiss you’ve ever had and why?',
      'What’s the most embarrassing wardrobe malfunction you’ve ever had?',
      'What’s the CoupleDirtytest body part on a guy?',
      'What’s the CoupleDirtytest body part on a girl?',
      'What’s the awkwardest crush you’ve ever had on someone?',
      'Describe the sexual encounter you regret the most.',
      'What was it like the first time you went down on someone?',
      'Spit or swallow?',
      'How often do you shave down there?',
      'Have you ever gotten a wax down there?',
      'If you were going to have a threesome, would you want the third party to be another girl or a guy?',
      'Have you ever been to a strip club?',
      'What’s something funny that turns you on?',
      'Do you get more horny when you’re on your period?',
      'Do you mind the taste when you go down on someone?',
      'Does body count matter to you?',
      'Would you ever go to a strip club?',
      'Have you ever tried to stick something that’s not a sex toy into your vagina?',
      'How old were you when you masturbated for the first time?',
      'Do you get turned on by nipple play?',
      'Have you ever had sex on your period?',
      'Do you enjoy having sex on your period?',
      'Which position is your least favorite and why?',
      'Which position is your favorite and why?',
      'Do you enjoy anal play?',
      'What time of day do you prefer to have sex during?',
      'Where’s the most embarrassing place you’ve ever gotten a boner?',
      'What’s the CoupleDirtytest body part on a girl?',
      'What’s the CoupleDirtytest body part on a guy?',
      'Which male celebrity is the CoupleDirtytest in your opinion?',
      'Which celebrity would you do in an instant if you had the chance?',
      'When’s the last time you cried?',
      'What break-up broke your heart the most?',
      'What’s the craziest sex you’ve ever had?',
      'Have you ever gotten head while driving?',
      'Do you find lingerie CoupleDirty?',
      'How old were you when you had your wet dream?',
      'Do you like to go all night or lay it all out in one fail swoop?',
      'Have you saved nudes from old hookups or exes?',
      'Do you like sending nudes?',
      'Does body count matter to you on your partners end?',
      'What’s your favorite position and why?',
      'What time of day is your favorite to have sex during?',
      'Have you ever gotten blue balls?',
      'What’s the strangest thing you’ve ever gotten aroused from?',
      'Have you ever owned or used a blow up doll?',
      'Have you ever worn a sexy piece of clothing?',
      'What’s the most romantic date you’ve ever been on?',
      'Have you ever tried to go down on yourself?',
      'Eat a snack in the sexiest way possible.',
      'Act out your favorite position with objects in the house.',
      'Demonstrate putting on a condom using a household object or food.',
      'Put something in your shirt and pretend to have boobs until the next round is over.',
      'Dye your hair a crazy color.',
      'Spank yourself while calling yourself a “bad boy” for 20 seconds.',
      'Give your best impression of a sexy school girl.',
      'Can you ever watch your partner have sex with someone else?',
      'Are you in love with your partner?',
      'What was your first sexual impression on your partner?',
      'Did you first have lust or love for your partner?',
      'Would you ever get bored of having sex with your partner?',
      'Do you have a friend you’re attracted to?',
      'How many days a week will you have sex?',
      'Who is your partner’s least attractive friend?',
      'Who is your partner’s most attractive friend?',
      'What is your partner’s most annoying sexual habit?',
      'What is your partner’s sweetest trait during sex?',
      'What is your favorite body part of your partner?',
      'When was the first time you were attracted to me?',
      'Have you ever wanted to try tying me down to the bed?',
      'What’s the dirtiest thing you’ve ever imagined doing to me?',
      'Have you ever pictured me naked?',
    ],
    dare: [
      'Fake your best orgasm in front of me.',
      'Do a mini strip tease by taking off some of your clothing in front of me.',
      'Post something raunchy on your preferred social media app and you can’t remove it until the next round is over.',
      'You’ve been naughty, time to be put in time out on my lap for the next round.',
      'Talk in a raunchy accent until your next turn.',
      'Scroll blindly through your contacts and whoever you land on, say one sexy thing about them.',
      'Give your best impression of a naughty cop who’s trying to arrest someone for being too sexy.',
      'Send bold, dirty message to someone you’ve hooked up with before.',
      'Take a pen and paper and draw your penis or vagina.',
      'Fake a blowjob on a bottle.',
      'Describe your favorite position in detail but without saying what it is. Let me guess it!',
      'Have your partner read through your browsing history in a sexy voice.',
      'Make a sexy song playlist with your partner.',
      'Sexily wash your partner’s feet.',
      'Be blindfolded and tickled or lightly touched for one minute.',
      'Have your partner close their eyes and try to turn them on only using sounds.',
      'Try to turn on your partner by blowing on the back of their neck, alternating between cold and CoupleDirty.',
      'Place a hand in your partner’s underwear for the next round and try to arouse them.',
      'Draw something on your partner’s back. If they guess correctly, they get a special favor of their choosing, if not, you get one.',
      'Your partner gets to dress you up in their clothes and take a pCoupleDirtyo.',
      'Call the parents of your partner and express to them how much you adore your partner.',
      'Give your partner a CoupleDirty lap dance.',
      'Whisper something not sexy into your partner’s ear but try to make it sound CoupleDirty.',
      'Describe your partner’s naked body in intense, erotic detail.',
      'Wear handcuffs or have your hands tied for a few turns.',
      'Trade clothes with your partner.',
      'Take a body sCoupleDirty off your partner.',
      'Show your partner your go-to porn video.',
      'Give your partner a sexy full-body massage.',
      'Give your phone to your partner and let them order something CoupleDirty for you to wear.',
      'Turn on your partner by only touching their arms and hands.',
      'Lick something yummy off your partner’s body part of choice.',
      'Take off a piece of your partner’s clothing, only using your teeth.',
      'Trace your partner’s body with an ice cube that’s being held in your mouth.',
      'Beg your partner to do naughty things to you. It better be convincing!',
      'Give your partner head with their clothes on.',
      'Do whatever your partner says for one minute.',
      'Put on the CoupleDirtytest song you know and try to seduce your partner with it.',
      'Make your best orgasm face and let your partner take a pCoupleDirtyo of it. This is your lock screen for the next 24 hours.',
      'Become a sexy chef while teaching your partner how to make a fun late night snack while just wearing an apron.',
      'Find an old pCoupleDirtyograph and try to recreate it together.',
      'Have your partner ask 2 questions about themselves that you should know the answers to. If you get them right, you get a reward. If you get them wrong, you get punished.',
      'Have your partner take a picture of you looking naughty.',
      'Give your partner a massage without using your hands.',
      'Act out how you remember your first date in 20 seconds.',
      'Lick your partner’s feet for 25 seconds.',
      'Set a timer and try to make your partner orgasm in 5 minutes.',
      'Set a timer for 2 minutes and try not to get turned on by whatever your partner decides to do to you.',
      'Watch porn together and try to imitate what you see on the screen.',
      'Perform a strip tease for your partner.',
      'Lick your partner’s nipples.',
      'Kiss your partner in the sexiest place and sexiest way possible.',
      'Undress your partner with one hand.',
      'Suck on your partners finger like you’re giving them head.',
      'Send a naughty text message to your partner.',
      'Become a sexy chef and spank your partner sexily with an item from the kitchen.',
      'Arouse your partner by only using your tongue.',
      'Attempt to make a sex tape with your partner.',
      'Let your partner blindfold you and do what they want to you for a minute.',
      'Bend your partner over your knee and spank them while telling them they’re a bad boy/girl.',
      'Sexily perform good foreplay on your partner’s ear to get them aroused.',
      'Dress up in something your partner would find sexy.',
      'Turn on your partner by sexily sucking on their finger.',
      'Have your partner lay down and kiss them upside down the best you can.',
      'Give your partner a lesson on giving head to them with an object from the kitchen.',
      'Have your partner spank you as hard as they can.',
      'Whisper a sexy name in my ear that you’ve never called me but have thought about trying.',
      'Use a sex toy to try and get your partner in the mood.',
      'Have your partner blindfold you and touch you with a part of their body. If you guess what part of their body they’re touching you with, you get a special reward.',
      'Seduce your partner in a room where you have never had sex before.',
      'Let your partner pick what profile picture you get to have for the remainder of the evening.',
      'Demonstrate how you masturbate on an object in your room.',
      'Give a tutorial on your best sexual technique on something in your room.',
      'Slap yourself somewhere CoupleDirty.',
      'Order your partner something to eat and they have to try whatever it is.',
      'Change into the CoupleDirtytest outfit you have and pose in it like a model.',
      'Cut off a little bit of your hair.',
      'Draw something on your face with marker.',
      'Try being sexy while holding your tongue and talking.',
      'Pick two things from your kitchen and use them to act out your favorite sex position.',
      'Order something sexy to wear when you see the other person.',
      'Take off your bra with one hand and without taking off your shirt.',
      'Put an object in your pants and act like it’s your junk.',
      'Wear your bra on your head like a hat for the rest of the game.',
      'Post a pCoupleDirtyo of a tampon on social media and don’t take it down until your next turn.',
      'Practice a sexy dance on a piece of furniture in the room.',
      'Shave part of your eyebrow.',
      'Dye part of your hair a daring color.',
      'Fake an orgasm for 20 seconds.',
      'Do a sexy crawl towards someone else in the room.',
      'Pretend to be any animal in a sexy way.',
      'Redress yourself in a guy’s clothing.',
      'Give a tutorial with an object in the room on how to pleasure a woman.',
      'Imitate how a guy flirts for 20 seconds.',
      'Kiss your favorite part on your partner’s body.',
      'Sing you and your partner’s favorite song.',
      'Do an impression of your partner.',
      'Put a strawberry in your mouth and eat it with your partner.',
      'Say something sexual in code that only your partner will understand.',
      'Tell your partner something that will turn them on',
      'Take off your partner’s shirt only with your teeth.',
      'Try not to look at your partner for 2 minutes.',
      'Give your partner an Eskimo kiss.',
      'Do an impression of your partner’s best friend.',
      'Turn on your partner without touching them.',
      'Be your partner’s slave for five minutes.',
      'Lick syrup off your partner’s best body part.',
      'Make out with your partner until the next round.',
      'Brush your partner’s teeth.',
      'Sit on your partner’s lap until the next round.',
      'Make a one minute song about your partner.',
      'Give your partner a foot massage.',
      'Switch underwear with your partner.',
      'Strip in front of your partner.',
      'Smack your partner’s booty.',
      'Suck your partner’s toes for one minute.',
      'Eat strawberry from your partner’s underwear.',
      'Call your partner’s ex.',
      'Bite your partner’s bottom lip.',
      'Go through your partner’s cell phone.',
      'Massage your partner’s back.',
      'Give your spouse your phone for two minutes to do what they want.',
      'Your partner has to use a picture of your orgasm face as their lock screen for 24 hours.',
      'Put an ice cube on your partner’s private for one minute.',
      'Take a shot for every time you forget your anniversary.',
      'Take a shot for every time you forget your partner’s birthday.',
      'Whisper anything hot and steamy into your partner’s ear.',
      'Give your partner a full body massage.',
      'Kiss your partner somewhere new 5 seconds for a minute.',
      'Lick whipped cream off your partner stomach.',
      'You have to beg your partner to spank you.',
      'Take a naughty picture with your partner.',
      'Tease your partner a bit.',
      'Give your partner a naughty dance without pants on. ',
      'Do a striptease for your partner.',
      'Massage your partner’s neck with your mouth.',
      'Massage your partner’s back with your mouth.',
      'Tell me one secret no one knows about you.',
      'Is there anything you’d like me to do?',
      'Suck on my fingers and pretend you’re doing oral.',
    ],
  },
};

export default CoupleDirty;
