const TabooKinky = {
  name: 'Everyone',
  title: 'Top Kinky & Taboo Truth or Dares for',
  description: `Thought Truth or Dare was just a game for teens who want to embarrass each other? Think again. It’s also perfect for couples who want to spice things up a little bit.<p> Today, I'm going to show you some really hot and dirty truth questions or dares for your boyfriend, girlfriend, or partner to keep things fun, exciting, and, most importantly, never boring. There are tons of ways to spice up your sex life, but asking kinky truth or dare questions is the perfect way to very quickly find out more about each other (on a very deep level) while also very quickly learning about each other's kinks, desires, and fantasies.</p><p> Don't worry! This list of unique dirty truth or dare questions will be ideal for you.</p>`,
  content: {
    truth: [
      'What has been your best sexual experience?',
      'What was the last time you gave head?',
      'What is the longest time you’ve ever given head?',
      'Have you ever done a threesome?',
      'Would you ever do a threesome?',
      'What’s your take on sex in groups?',
      'Can you ever watch your partner have sex with someone else?',
      'How many partners have you had at one time?',
      'Give a description of how your orgasm feels.',
      'Where’s your favorite place to make out?',
      'Have you ever done the backdoor style, and would you?',
      'What is the longest time you’ve gone without sex?',
      'Do you prefer rough or slow sex?',
      'Do you like to be on top or beneath?',
      'What is your favorite sex position?',
      'Do you prefer anal?',
      'What sex position do you dislike?',
      'What is your worst sexual experience?',
      'Have you ever had sex outdoors?',
      'What is the strangest place you can ever have sex?',
      'Have you ever done oral on a stranger?',
      'Have you ever paid someone to have sex with you?',
      'Who was your first sexual partner?',
      'Have you ever made a sex tape?',
      'Do you have a favorite porn star?',
      'Do you have a favorite strip club?',
      'Have you ever stripped before?',
      'Do you like to do it with the light on or off?',
      'Does size matter to you?',
      'Do you like to have music in the background or not?',
      'Do you like your partner to be silent or loud?',
      'Do you like a little bit of foreplay?',
      'What’s your favorite part of foreplay?',
      'Have you ever tried role-playing?',
      'Do you have a sweet spot?',
      'What is your weirdest sexual fantasy?',
      'Would you ever have sex with someone for money?',
      'Are you flexible in bed?',
      'What is the highest number of orgasms you’ve had in one sexual encounter?',
      'Would you spit out or swallow?',
      'How many sexual relationships have you been in before?',
      'Have you ever thought of sleeping with someone else?',
      'Have you slept with anyone on campus?',
      'What’s your GPA?',
      'What was the craziest thing you did in your freshman year?',
      'Have you ever made love with a professor?',
      'Have you ever passed out from too much booze?',
      'What’s the craziest thing you did while drinking?',
      'What’s your dirty little secret?',
      'What’s the craziest place you’ve made love on campus?',
      'Do you like your roommate sexually?',
      'What is your roommate’s best body part?',
      'Have you ever had sex in your roommate’s bed?',
      'Have you ever considered sleeping with a roommate?',
      'How many pool parties have you been to so far?',
      'What’s the craziest pool party you’ve been to?',
      'Have you ever had a threesome?',
      'Have you ever hosted a pool party?',
      'Did you smoke or drink before you got to college?',
      'Have you ever stripped for money?',
      'Have you ever had sex with your friend’s partner?',
      'Have you ever had sex for money?',
      'Have you ever considered having an orgy?',
      'Have you ever had an orgy?',
      'Have you ever used a sex toy?',
      'What’s the longest sex you’ve had?',
      'What’s the highest amount of shots you’ve had in one night?',
      'Have you ever wet your bed when drunk?',
      'What’s the longest you’ve gone without sex?',
      'When was the last time you skipped class?',
      'How many times have you skipped class?',
      'Have you ever woken up to a stranger in bed?',
      'How old were you when you started drinking?',
      'Have you ever wondered what a professor looked like naked?',
      'Have you ever slept with a freshman?',
      'Have you ever slept with someone for money?',
      'Have you slept with a freshman?',
      'Have you ever imagined your roommate naked?',
      'Have you ever fought with someone you were sexually attracted to?',
      'Have you ever fantasized about sleeping with a professor?',
      'If you were to have a threesome with anyone in the room, who would it be?',
      'What’s your nastiest browsing history?',
      'Have you ever sexted anyone before?',
      'What sexual adventurous thing have you always wanted someone to do to you?',
      'What’s an illegal thing you wished was legal?',
      'What’s your favorite sexual fantasy?',
      'When was the first time you came?',
      'When was the last time you came so good?',
      'Do you have a favorite sex toy?',
      'Where’s the weirdest place you’ve ever had sex?',
      'When was your first kiss with someone?',
      'Who has been your best partner so far?',
      'What’s your favorite body part of the opposite gender?',
      'What’s your favorite body part on yourself?',
      'Have you ever cheated before?',
      'How many people have you slept with?',
      'Are you jealous of anyone?',
      'Do you like angry sex?',
      'Do you like makeup sex?',
      'How many exes do you have?',
      'How many people have you kissed?',
      'How many people have you had sex with?',
      'Have you ever been so turned on that you couldn’t control it?',
      'Have you ever touched yourself?',
      'Have you ever had sex at work?',
      'Do you like being in control in bed?',
      'Do you prefer being controlled in bed?',
      'How far have you gone for sex?',
      'What’s the highest number of sexual intercourse you’ve had in a day?',
      'Have you done it in people’s presence without them realizing it?',
      'What kind of foreplay do you like?',
      'Would you take a hot shower with me?',
      'Have you ever tried to feel someone up when hugging?',
      'What got you hot for the first time?',
      'What gets you hot every single time?',
      'How bad have you always wanted to tear off my clothes?',
      'Do you watch naughty movies?',
      'How bad do you want to pull my hair?',
      'Do you like being kissed on the neck?',
      'Have you ever thought about me when showering?',
      'What naughty things do you keep in your nightstand?',
      'Whats your favorite piece of clothing?',
      'Is your browsing history clean?',
      'Are you achieving your goals so far?',
      'Did you ever fantasize about someone older than you?',
      'Have you ever put anything weird on your body?',
      'When was the first time you ever watched porn?',
      'When was the last time you watched porn?',
      'What’s your wildest sexual fantasy?',
      'How did you feel when someone went down on you for the first time?',
      'Have you ever been attracted to a girl?',
      'Have you had a terrible kiss before?',
      'What’s the most fun you’ve had on a date?',
      'Have you ever done anything romantic that you’re proud of?',
      'What’s your favorite male body part?',
      'What’s your worst wardrobe malfunction?',
      'Have you ever felt embarrassed by a crush?',
      'What was it like going down on someone for the first time?',
      'Have you ever faked an orgasm?',
      'How does it taste when you go down on someone?',
      'Have you ever regretted a hookup?',
      'Have you ever regretted doing anything for love?',
      'How often do you trim down there?',
      'Have you ever gotten a bikini wax?',
      'Have you ever had a threesome?',
      'Will you ever have a threesome?',
      'Do you have any fetishes?',
      'Have you ever had a sex dream about any guy I know?',
      'Have you ever gone to a strip club?',
      'Have you ever stripped for cash before?',
      'What’s your most powerful sexual experience?',
      'When did you lose your virginity?',
      'Name one thing you’ve wanted to try so bad with a guy?',
      'Have you ever has a one night stand?',
      'What’s the weirdest thing that turns you on?',
      'What’s your favorite body part on a girl?',
      'What’s the most embarrassing moment you got turned on?',
      'Have you ever thought of having sex with a guy?',
      'What’s the craziest thing you ever did for love?',
      'Have you ever been embarrassed about something you did for love?',
      'Have you ever had a crush on someone out of your league?',
      'Have you ever cheated?',
      'Have you ever cried for love?',
      'Have you ever made someone cry?',
      'Have you ever had a threesome?',
      'Have you had a sex dream about anyone I know?',
      'Would you ever have a threesome?',
      'Have you ever had an orgy?',
      'Would you ever have an orgy?',
      'Have you ever had sex in a car?',
      'When did you lose your virginity?',
      'What do you wish to try in the bedroom?',
      'Have you ever been given head while driving?',
      'How do you like lingerie, a little reveal, or no reveal?',
      'Have you ever done role play before?',
      'Do you like second rounds or are they exhausting?',
      'What’s the worst lie you’ve ever told a girl?',
      'Do you have any steamy videos on your phone?',
      'Do you have any hot photos on your phone?',
      'How many people have you seen naked?',
      'Mention one thing you’ve wanted to do so bad with a girl?',
      'What’s the craziest sex dream you’ve had?',
      'Have you ever had a bad experience with alcohol?',
      'What was the last video you watched on YouTube?',
      'What color is your underwear?',
      'What are the naughtiest things you’ve ever done so far?',
      'Tell everyone anything your mum doesn’t know about you?',
      'What’s your most embarrassing fart story?',
      'What did you want to be when you were little?',
      'What’s the dumbest statement you’ve ever made?',
      'What’s the dumbest statement I’ve made so far?',
      'When was your sexual awakening?',
      'When was your best sexual experience?',
      'When was your first sexual experience?',
      'What was your wildest sexual experience?',
      'What’s the most sensual part of your body that you like to be kissed?',
      'What’s the worst thought you’ve had so far?',
      'What is the best news you’ve ever gotten?',
      'What’s the naughtiest activity you’ve done at work?',
      'Have you ever cried because of anyone?',
      'What is your favorite belonging?',
      'What are your major body-part insecurities?',
      'What naughty things have been on your mind lately?',
      'What naughty things are you thinking about right now?',
      'What are your biggest sexual fears?',
      'Has there been anyone who got away during sex?',
      'Have you dyed your pubic hair before?',
      'What color are you open to dye your pubic hair to?',
      'Are you turned on right now?',
      'Do you like being tied up?',
      'What’s the number one activity you hate in bed?',
      'Where would you like to be massaged?',
      'Do you have any funny sexual experiences?',
      'Have you ever had sexual intercourse in public?',
      'Would you sleep with any of your exes again?',
      'What’s the hottest thing someone has done to you?',
      'Name one activity you wished someone did to you?',
      'Who is the love of your life?',
      'Who used to be the love of your life?',
      'What’s one naughty secret that most people can never find out about you?',
      'Have you ever done something sexual you felt really guilty about?',
      'What’s one secret only close friends know about?',
      'Have you ever had a disappointing sexual experience?',
      'Have you ever been turned down sexually?',
      'What’s that one item you’ve kept since childhood? ',
      'What’s the most fun object in your bedroom?',
      'What’s the weirdest item in your room right now?',
      'The worst sexual mistake you’ve ever made?',
      'Where are your favorite romantic places?',
      'Have you ever made out with someone of the same gender?',
      'Have you ever slept with someone of the same gender?',
      'How many adult toys have you had?',
      'Have you sexted someone before?',
      'Have you ever picked your nose during sex?',
      'What’s the weirdest stuff you do by yourself?',
      'What’s the craziest stuff you do all alone?',
      'Who do you currently find extremely attractive?',
      'Which one of your friends turns you on the most?',
      'Which one of your friends turns you on the least?',
      'Have you ever farted during sex?',
      'Have you ever took a break during sex?',
      'Have you ever grabbed a snack during sex?',
      'Have you ever been bored during sex?',
      'When was the last time you peed or pooped your pants?',
      'Have you ever done anything illegal?',
      'What sex act do you wish you could erase from your memory?',
      'What sexual activity are you never going to do again?',
      'What’s the shortest time you’ve known someone before sleeping with them?',
      'What’s the weirdest sexual fantasy you’ve had about someone?',
      'Who’s the weirdest person you’ve had a sexual fantasy about?',
      'What sexual activity do you think is overhyped?',
      'If you had to choose between oral and penetration forever, which one would you go with?',
      'Do you prefer to be in love and be intimate or just strangers?',
      'Who’s the oldest person you’ve slept with?',
      'Can you remember the full names of everyone you’ve slept with?',
      'What’s your sexual goal for now?',
      'Have you ever slept with a virgin?',
      'Would you rather be on top or beneath?',
      'Where turns you on, on the opposite gender?',
      'What do you like doing in bed, but others dislike it?',
      'What’s the sexiest statement you’ve heard from someone?',
      'What’s the most unintentionally least appealing thing you’ve heard from someone?',
      'Would you prefer to give unlimited orgasms, or receive?',
      'What type of porn have you watched?',
      'What age do you think is too old to be a virgin?',
      'Name on sexual superpower you wish you had.',
      'What character in a movie do you have sexual fantasies about?',
    ],
    dare: [
      'Do a striptease in front of everyone and on the table.',
      'Tie a cherry stem with only your tongue.',
      'Get on your partner and start riding.',
      'Take off your clothes and start twerking in your underwear.',
      'Lick your partner from their neck all the way to their middle region.',
      'Suck on your partner’s belly button for thirty seconds.',
      'Suck on your partner’s nipple for a minute.',
      'Put a piece of candy in your mouth and unwrap it.',
      'Remove your partner’s underwear with only your mouth.',
      'Kiss around your partner’s lower region.',
      'Place your hand in your partner’s pants for a minute.',
      'Kiss one person seated next to you.',
      'Sit in your partner’s stuff until the next round. ',
      'Spoon your partner until the next round.',
      'Give your partner a head for one minute.',
      'Run an ice cube on your partner’s body for a minute.',
      'Bite your partner’s booty.',
      'Kiss your partner’s booty.',
      'Lick whipped cream off someone’s body part.',
      'Take off all your clothing for the rest of the game.',
      'Sit naked for the rest of the game of truth.',
      'Send a naked selfie to your partner.',
      'Make a naughty video with your partner.',
      'Kiss your partner’s private.',
      'Stand outside naked for one minute.',
      'Have sex for only 3 minutes, and you have to stop with the timer stops.',
      'Take off your partner’s bra with your teeth.',
      'Send a nude to your ex.',
      'Wear your partner’s underwear.',
      'Give your partner a back rub.',
      'Do whatever the next person has always wanted for fifteen minutes.',
      'Do what the entire group says for fifteen minutes.',
      'Your partner has to rub your inner thighs.',
      'Put a hickey on the inner thighs of someone in the group.',
      'Give your partner an orgasm in two minutes.',
      'Undress and wear the first thing you find in the closet.',
      'Hop into the shower for two minutes.',
      'Run-on the street with your underwear.',
      'Give one person to your right a hickey.',
      'Slap the next person’s booty.',
      'Feed someone a pack of dry noodles.',
      'Take a picture of the next person in their underwear.',
      'Lick someone’s toe.',
      'Eat toilet paper.',
      'Twerk on someone.',
      'Make a freestyle about everyone in the room.',
      'Give someone a lap dance without any clothing on.',
      'Make a prank call and say something naughty.',
      'Twerk on the floor.',
      'Take someone’s shirt off with your teeth.',
      'Kiss the next person to you.',
      'Eat the first thing you find in the fridge.',
      'Give someone head with their underwear on.',
      'Someone should give you a sexy dance while you’re blindfolded.',
      'Drink an entire beer in 5 minutes.',
      'Raise your shirt and play with your nipples',
      'Lick someone’s face',
      'Walk outside completely naked.',
      'Do a striptease with high heels on.',
      'Sit in a trash can for ten minutes.',
      'Fake an orgasm in front of everyone.',
      'Kiss one person you touch while blindfolded.',
      'Leave a sexy voicemail to your ex.',
      'Lick peanut butter off someone’s body.',
      'Go skinny dipping with someone in the group.',
      'Pretend to make a game plan to sleep with someone in the room.',
      'Everyone has to feed you and you have to reply with, Thank you, Daddy. ',
      'You have to do a timeout on someone’s lap.',
      'You have to order a sex toy off Amazon.',
      'Act out your favorite sex position.',
      'You have to undress and take a shot for every piece of clothing you want to keep on.',
      'Trace your fingers on someone’s lip and whisper something naughty.',
      'Dare someone to change their Facebook status to, I’m cumming….',
      'You have to wear a swimming suit for the rest of the night.',
      'Give someone a back massage while kissing their back.',
      'Place your hand on the inner thigh of the person next to you.',
      'Wash your crush’s feet.',
      'Tickle your crush for a minute.',
      'Try your crush on with only sounds and without lights.',
      'Get extremely close to your crush and say something dirty to their face.',
      'Blow hot and cold air on their neck for one minute.',
      'Write out something secret on their back, and they have to guess it right. If they don’t, they’ll do something for you.',
      'Dress your crush up in your clothing.',
      'Call your parents and tell them you love someone.',
      'Call your crush’s parents and tell them you love them.',
      'Do a sexy belly dance using only one leg.',
      'Fake a British accent.',
      'Do whatever the group tells you for one minute.',
      'Give everyone a foot massage.',
      'Dance to some music without pants on.',
      'Take off your bra with your shirt on.',
      'Make out with the third person to your right. ',
      'Send your spouse your naked picture.',
      'Act a passionate kissing scene from a movie with the player on your right.',
      'Fake an orgasm for thirty seconds.',
      'Put some socks in your pants and pretend it’s your penis for a minute.',
      'Act out your favorite sex move.',
      'Kiss your best friend in the room for thirty seconds.',
      'Give any girl a foot massage in the room.',
      'Put some ice cubes into someone’s bra for five minutes.',
      'Take off your bra for the rest of the night.',
      'Draw someone’s face on your belly button.',
      'Put a bra on your head for the rest of the night.',
      'Take off your pants and put on some heels.',
      'Do a sexy dance with a broom. ',
      'Do jumping jacks for a minute.',
      'Touch someone’s tongue with yours.',
      'Demonstrate fingering someone.',
      'Do 5 squats on the front porch.',
      'Wear the first thing you see in the closet.',
      'Try to market your favorite naughty toy.',
      'Do a sexy crawl on the ground.',
      'Act out how to woo a lady.',
      'Talk about your penis like it was a person.',
      'Reenact sounds from your last sexual encounter.',
      'Hit on someone in the group like at a bar.',
      'Try to make different possible sounds with your lips.',
      'Make different possible fart sounds with your underarm.',
      'Explain how to wear a condom using a banana.',
      'Put ice cubes in your mouth until they melt.',
      'Eat anything in the kitchen as sexily as possible.',
      'Tell your best friend some nasty words in his ear.',
      'Give someone a foot massage in the room.',
      'Act like you’re having sex with the couch for a minute.',
      'Read a book in the most seductive way possible.',
      'Make out with your hand to a romantic country song.',
      'Put on some headphones and dance to your favorite song.',
      'You have to hold water in your mouth until the round finishes.',
      'Slap your behind and talk about how bad you’ve been.',
      'Feed someone some strawberries using only your mouth. ',
      'Draw something nasty on your face.',
      'Grind to your pillow for a minute.',
      'Feed someone almond with your mouth.',
      'Passionately play an air guitar for one minute.',
      'Demonstrate your best sexual position with signs.',
      'Walk outside in your underwear.',
      'Walk outside naked.',
      'Change into the hottest outfit you have.',
      'Put your butt on your phone for thirty seconds.',
      'Sing opera.',
      'Take off any three items from your body.',
      'Draw anything silly on your face.',
      'Cut some parts of your hair.',
      'Make a silly video in your underwear and post it on Instagram.',
      'Make three sensual hand gestures.',
      'Read a dirty part from a romance novel.',
      'Talk dirty for thirty seconds.',
      'Dance dirty to any song on your phone.',
      'Show three embarrassing spots on your body.',
      'Draw a mustache on your face.',
      'Try to recreate a kissing scene from a movie.',
      'Demonstrate your favorite sexual position.',
      'Pleasure yourself with ice cubes all over your body.',
      'Lick your phone screen for ten seconds.',
      'Try to act seductive for the next 2 minutes.',
      'Try to turn someone on with only your eyes.',
      'Eat your favorite snack seductively.',
      'Try to juggle any three items.',
      'Show your underarms.',
      'Do a funny freestyle about the next person.',
      'Give someone access to your dating profile to do what they want for fifteen minutes.',
      'Make a sandwich and feed it to someone.',
      'Someone picks a hilarious new nickname for you.',
      'Call someone on your contact list and tell them you love them.',
      'Put an embarrassing picture as your profile picture.',
      'Do a fast dance to a slow song.',
      'Eat your food without cutlery.',
      'Kiss someone’s belly button.',
      'Smell someone’s shoe for two minutes. ',
      'Sing a song you’ve made love to.',
      'Randomly select anybody on your contact and say something hot about them.',
      'Send a seductive message to someone on your contact list.',
      'Lick another person’s lips and they have to resist kissing back.',
      'Talk dirty to someone for two minutes',
      'Wear a blindfold and kiss whatever body part is put in front of you.',
      'Lick anything sweet off someone’s neck.',
      'Take a seductive selfie and send it to someone in the room. ',
      'Send a seductive message to someone you’ve slept with.',
      'Whisper anything to the next person that will turn them on.',
      'Undress someone with only one hand.',
      'Use an adult toy for 60 seconds.',
      'Take off your underwear for the rest of the night.',
      'Show everyone the sexiest picture you have on your phone.',
      'Put whipped cream on your body, and allow someone to lick it off.',
      'Sleep with someone in a room you’ve never done it before.',
      'Try to make someone orgasm in five minutes.',
      'Kiss someone’s neck for thirty seconds.',
      'Try to arouse someone without touching any sensual places.',
      'Use your tongue to spell out anything on someone’s body.',
      'Kiss someone’s earlobe for thirty seconds.',
      'Whisper to someone anything you’ve wanted to do with them.',
      'Show everyone the dirtiest message you have on your phone.',
      'Perform a motorboat on someone. If you’re a girl, have someone do it to you.',
    ],
  },
};

export default TabooKinky;
