// prettier-ignore
const Teens = {
  name: 'Teens',
  title: 'Best Truth or Dares for',
  description: `Truth or Dare is a game that is enjoyed by people of any age. Teenagers would love playing this game. Read this article to know 180+ interesting truth and dare questions for teens.<p> ENJOY PLAYING THE GAME!</p>`,
  content: {
    truth: [
      'Who was your first crush at school?',
      'Who is the most beautiful girl at school?',
      'Who is the most handsome guy at school?',
      'What’s your idea of a perfect date?',
      'Where would you like to go on a first date?',
      'Do you have a boyfriend?',
      'How many boyfriends have you had?',
      'Have you been kissed yet?',
      'When did you have your first kiss, and with who?',
      'Did you ever break your girlfriend’s heart?',
      'Did you ever break your boyfriend’s heart?',
      'Was your heart ever broken by your boyfriend?',
      'Was your heart ever broken by your girlfriend?',
      'If you could go out on a date with a celebrity, who would it be?',
      'If you are stranded on a remote island, who would you choose for company?',
      'If you had to go out on a date with one of us in the room, who would it be?',
      'Of all the people you have dated, who has the most beautiful eyes?',
      'Tell us about your most embarrassing date?',
      'What was your most awkward moment on a date?',
      'Who do you think is the most beautiful teacher at school?',
      'Who do you think is the most handsome teacher at school?',
      'Did you ever have a crush on any of your best friend’s boyfriends?',
      'Did you ever have a crush on any of your best friend’s girlfriend?',
      'Have you ever flirted with your best friend’s siblings?',
      'Would you use a dating website?',
      'If you had to pick one of us to go on a prom date, who would it be?',
      'Are you obsessed with a celebrity?',
      'Would you break up with someone by sending them a text?',
      'Have you ever broken up with someone by sending them a text?',
      'Are you jealous of someone because of who they date?',
      'How would you want the love of your life to propose to you?',
      'What kind of a person would you want to be married to in the future?',
      'Have you ever fallen in love with someone at first sight?',
      'Who is your best friend?',
      'Did you ever lie to your best friend/bud?',
      'Did you make your best friend do something for you by lying?',
      'Would you lie or cheat for a friend?',
      'What would you do if you had a crush on your bestie’s girlfriend?',
      'What would you do if you had a crush on your bestie’s boyfriend?',
      'Would you go behind your bestie’s back with a crush?',
      'Would you ditch a lunch date with your bestie to go on a date?',
      'Name one quality that you do not like in your friend.',
      'What do you like most about your best friend?',
      'What are the three most important qualities you look for in a friend?',
      'Who was the worst friend you have had and why?',
      'What is the cruelest thing you have done to a friend?',
      'Have you ever shared your best friend’s secrets with anyone else?',
      'Can you go for weeks or even months without talking to your bestie?',
      'Did you have an imaginary friend? What was his or her name?',
      'Did you ever cheat in a test?',
      'Did you actually enjoy reading a romantic poem in literature class but pretended that it was lame?',
      'What’s your career ambition?',
      'How confident are you about achieving your dreams?',
      'Which subject do you hate the most?',
      'Which is the most boring class you had to attend?',
      'Did you ever skip school by telling a lie and lie about it to your parents?',
      'Did you ever mock a teacher or classmate behind their back?',
      'What is the first thing you do after school every day?',
      'What is your favorite thing to do at school?',
      'Do you like gym class?',
      'Who is your favorite teacher and why?',
      'Have you ever played a prank on a teacher?',
      'How many times have you been punished and sent to the principal’s office?',
      'Who is the creepiest kid you know in school?',
      'What is the lowest/worst grade you got in school?',
      'Have you ever fallen asleep in class?',
      'Did you pretend to be sick so you can skip class or avoid a test?',
      'Who was the first boy that you kissed in school?',
      'Which college are you planning to go to?',
      'What would you do if you cannot get into the college of your choice?',
      'If you had the money and resources to start a business, what would it be?',
      'If you could invent something, what would it be?',
      'If you won a million dollars in lottery, what would you do with the money?',
      'If not here, where would you be and what would you be doing at this moment?',
      'Who is your role model and why?',
      'What’s your dream job?',
      'What’s your idea of a perfect vacation?',
      'Imagine this: you wake up one day and realize that you’ve become invisible. What will you do?',
      'If you had the chance to be reborn as someone in this room, who would it be?',
      'If you could be born again, what would you choose to be born as?',
      'What is your worst fear?',
      'If you had just 24 hr to live, how would you spend your day?',
      'If you had the chance to live on your own right now, would you take it?',
      'What is the one thing you would change in your life if you had the option?',
      'If you had one wish, what would you wish for?',
      'If you knew that the world was going to end soon, what would you do?',
      'If you were a superhero, what would your power be?',
      'Would you rather be a princess or a mermaid?',
      'What would you do if you were the Queen of England?',
      'Would you become a boy (or girl) for a day, if you had the choice? Why?',
      'If your parents went out of town for a week and you had the house to yourself, what would you do?',
      'What was the worst day of your life and why?',
      'What was the weirdest/strangest dream you have ever had?',
      'What is the one question you do not want to be asked in this game? (I will remember this for later!)',
      'Rate everyone in this room, on a scale of one to ten.',
      'List five disgusting/annoying habits you have?',
      'What is your weight?',
      'Have you ever stolen something?',
      'Did you let someone else take the fall for something you did?',
      'What was your childhood nickname?',
      'What is the most embarrassing thing that your parents caught you do?',
      'What was the stupidest thing you ever did?',
      'How long have you gone without showering/shaving?',
      'Did you ever pee in the swimming pool, while swimming?',
      'Did you ever spread a nasty rumor about someone else?',
      'What’s the weirdest thing you did when you were alone, in front of a mirror?',
      'What kind of pajamas do you wear to bed?',
      'What is the silliest thing that you are attached to and still posses?',
      'Did you ever watch an adult film and lie to your parents about it?',
      'What was the biggest lie you told without getting caught?',
      'If you were asked to make one of the people in this room your slave, who would you choose and why?',
      'Who looks sexier out of all the girls in the room?',
      'Who looks sexier out of all the boys in the room?',
      'Name one thing you hate in each of us.',
      'Who is the one person you hate most in the world?',
      'What do you do when you are alone at home?',
      'Do you have a journal?',
      'Have you ever cried because of anyone?',
      'What used to be your favorite cartoon character?',
    ],
    dare: [
      'Kiss the person to your left on the forehead.',
      'Go to the kitchen and eat a chili.',
      'Sing a song and do the hokey pokey in the center of the circle.',
      'Run around the room imitating a monkey or a gorilla.',
      'Pick someone from the group and dance with them to a love song.',
      'Kiss the pillow until it is your turn again.',
      'Wear your socks on your hands for the next three rounds.',
      'Paint each fingernail and toenail a different color and keep it for a day.',
      'Wear your pants backward for the rest of the evening.',
      'Apply makeup without looking into the mirror.',
      'Run in your place for the next two rounds.',
      'Pretend to be a pig and sniff the others in the group when it is their turn to speak.',
      'Paint your toenails with crayons.',
      'Gaze into one of the girl’s eyes for 30 seconds.',
      'Gaze into one of the boy’s eyes for 30 seconds.',
      'Slow dance to a fast song.',
      'Hop like a kangaroo for a minute and cover the entire room.',
      'Propose to your pet or the host’s pet in the most romantic way possible.',
      'Speak in a foreign accent for the next two minutes.',
      'Stand in the street and wave to every passerby for two minutes.',
      'Act like a dog and ask the others to pet you, like a dog.',
      'Walk like a runway model on the sidewalk.',
      'Hold a sign that says “Honk if you think I’m cute” and stand outside.',
      'Dance like crazy to your favorite song.',
      'For the next 5 minutes, you must say “oh, not again!” every time someone says the word “like”.',
      'Recite the alphabet backward.',
      'Beat an egg on your head.',
      'Eat a snack without using your hands.',
      'Make a funny hat and wear it on your head for the next two rounds.',
      'Stand in the chicken pose for the next two rounds.',
      'Eat a spoonful of mustard.',
      'Imitate each one of the members in the room.',
      'Act like your favorite teacher for the next 30 seconds.',
      'Eat as much hot sauce as you can.',
      'Fake Break up with your boyfriend.',
      'Fake Break up with your girlfriend.',
      'Fold yourself like a pretzel.',
      'Give the person to your right a piggyback ride.',
      'Do a belly dance.',
      'Act like the waiter and take snack order from every individual in the group.',
      'Call your parents and tell them that they are grounded for a week.',
      'Come up with a list of celebrities that each of the other players looks like in under two minutes.',
      'Sing the latest pop song in the worst possible way and post the video on YouTube.',
      'Tell a bad joke in a really excited tone!',
      'Put ice in your shirt and stay still until it melts.',
      'Try to lick your elbow while singing a song.',
      'Try to touch your nose with your tongue.',
      'Go out and say “I love you” to the first person you meet.',
      'Go out and sing a Disney song as loudly as you can.',
      'Borrow a cup of sugar from the neighbors.',
      'Make a video of you Moonwalking across the room and post it on YouTube.',
      'Ask the first person you meet outside on a date.',
      'Make a headdress out of toilet paper and promote it on Facebook!',
      'Say the alphabet backward in a British accent.',
      'For the next two rounds, sing whatever you want to say.',
      'Speak in rhyming words for the next three rounds.',
      'Repeat everything that the other players say for the next two rounds!',
      'For the next two rounds, speak like you were under water, gasping for air.',
      'Call up someone you have a crush on and tell them how much you like them!',
      'Use your elbows to update your Facebook status.',
      'Dance like a chicken on the lawn!',
      'Prank call a restaurant and order every item on the menu!',
      'Hold your shoe/or next person’s shoes to your nose for at least 30 seconds.',
      'Run around the house banging your chest and yodeling at the same time.',
      'Stand in the street and yell “I am (name)! Hear me roar!!”',
      'Combine a spoon of peanut butter and hot sauce and eat it.',
      'Smell the armpits of the person sitting to your right.',
      'Act like a puppy or a seal and let the others feed you.',
      'Sing a pop song as if you were in the opera.',
      'Go out the front door and do a dramatic death scene, like Daffy Duck of Bugs Bunny would do.',
      'Close your eyes, or get blindfolded and open the fridge door. Point to something and let the others feed you that!',
      'Go to the neighbor and ask for toilet paper.',
      'Call your boyfriend or crush and explain the rules of Monopoly to them.',
      'Call your crush and sing a love song like “I can’t help falling in love”.',
    ]
  },
};

export default Teens;
