const FORGIRLS = {
  name: 'Pickup lines for Girls',
  title: 'Top Tinder & Bumble Pick up lines for Girls',
  description:
    '<div><div>A good Tinder or Bumble ice breaker usually takes form in an open-ended question or joke that can easily lead into a fun conversation starter. It takes the awkwardness out of meeting people through a dating app and sets you up for success in the Bumble- or Tinder-verse!</div><br /><div>Need some inspiration for the next time you go swiping through dating apps? Take a peek at our favorite Tinder and Bumble pick-up lines, try out a few of your favorites, and see where things go!</div></div>',
  content: [
    'If a star fell from the sky every time I thought about you, then tonight the sky would be empty.',
    'I don’t have a library card, but do you mind if I check you out?',
    'Are you the sun? I’m about to get a sunburn looking at you.',
    'Hey, tie your shoes! I don’t want you falling for anyone else.',
    'Excuse me, but I think I dropped something. MY JAW!',
    'You must be a broom, ‘cause you just swept me off my feet.',
    'Are you google? because you’re everything I’ve been searching for.',
    'Aside from being sexy, what do you do for a living?',
    'Did it hurt when you fell from heaven?',
    'Are you Greek? Because you look like a goddess.',
    'Are you religious? Cause you’re the answer to all my prayers.',
    'Do you like coffee? Because I like you a latte.',
    'Are you a keyboard? Because you’re just my type',
    'I’m really glad I just bought life insurance because when I saw you, my heart stopped.',
    'Did your license get suspended for driving all these girls crazy?',
    'If you were a chicken, you’d be im-peck-able.',
    'Are you a bank loan? because you have my interest.',
    'If I could rearrange the alphabet, I’d put “U” and “I” together.',
    'Are you a parking ticket? Because you’ve got fine written all over you.',
    'Do you believe in love at first sight or should I walk by again?',
    'If you were a vegetable, you’d be a cute cumber.',
    'I’d never play hide and seek with you because someone like you is impossible to find.',
    'We’re not socks, but I think we’d make a great pair.',
    'You must be a hell of a thief because you stole my heart from across the room.',
    'If your heart was a prison, I would like to be sentenced for life.',
    'If you were a triangle, then you’d be acute one!',
    'Do i know you? You look a lot like my next girlfriend.',
    'I seem to have lost my phone number. Can I have yours?',
    'I was blinded by your beauty… I’m going to need your name and number for insurance purposes.',
    'I don’t believe in love at first sight, but I’m willing to make an exception in your case.',
    'If I could rearrange the alphabet, I’d leave it as it is. Some things are already at their best, that’s why I want you the way you are.',
    'Your lovely smile is a work of art that can’t be compared to the work of famous artists.',
    'You’re like a fine wine. The more of you I drink in, the better I feel.',
    'Do you believe in love at first sight? ’cause, if so, I’ll grab my bifocals.',
    'I think the gaps between my fingers were meant for yours.',
    'Do you have a bandaid? because I scraped my knee falling for you.',
    'If you were a page, you’d be fine print.',
    'Somebody better call God, because he’s missing an angel.',
    'If looks could kill, you’d be a weapon of mass destruction.',
    'You must be the square root of 2 because I feel irrational around you.',
    'Is it hot in here or is it just you?',
    'Drake would call you and I God’s plan.',
    'If I wasn’t jealous of the glass, I’d buy you a drink.',
    'Can I ask you a personal question? Beer or wine?',
    'After breaking the ice cube, the guy said to his crush, ‘can I buy you a drink now that I have broken the ice?’',
    'I see you’ve got some tequila. Does that mean you wanna give me a shot?',
    'Did you steal my beer? That one looks just like the one I was drinking.',
    'My buddies bet me that I wouldn’t be able to start a conversation with the hottest person&nbsp;in the bar.',
    'My drink is getting lonely, so would you like to join me with one?',
    'Did you drink soda? because you look so-da-licious.',
    'I see you’ve got some tequila. Does that mean you wanna give me a shot?',
    'Do you know what’s on today’s menu? It’s Me ‘n’ U.',
    'Kiss me if I’m wrong, but dinosaurs still exist, right?',
    'I wanted to take you to the movies but they don’t all you to bring your own snacks.',
    'Are you a magician? because whenever I look at you, everyone disappears.',
    'Could you please step away from the bar? You’re melting all the ice!',
    'I must be in a museum because you truly are a work of art.',
    'Something’s wrong with my cell phone because your phone number is not in it.',
    'Of all the beautiful curves on your body, your smile is my favorite.',
    'I guess your parents are bakers because they made you such a cutie pie.',
    'Does your father work at Nasa? because You’re a star!',
    'If you sneezed i wouldn’t even say god bless you because he clearly already did.',
    'Did we take a class together? I swear we could have chemistry.',
    'Do you have a map? because I keep getting lost in your eyes.',
    'It’s a good thing I have my library card, because i’m totally checking you out.',
    'Do you smoke pot? Because weed is cute together.',
    'Do you have overdue books? because you have fine written all over you.',
    'Honey, you give new meaning to the definition of ‘edible’.',
    'Do you have raisins? How do you feel about a date?',
    'I’m learning about important dates in history class. Wanna be one of them?',
    'Girl, your eyes are bluer than Heisenberg’s crystal.',
    'Are you a Grey’s Anatomy fan? because you’re definitely McDreamy.',
    'Are you a good cuddler? I might let you join my team.',
    'I want to use my coupons for free hugs on you.',
    'Do you like star wars? Because yoda only one for me!',
    'Do you like Harry Potter? Because I a-Dumbledore you!',
    'I’d love to be the diet Pepsi to your Sofia Vergara',
    'I’m not a stop along the way. I’m a destination.',
    'Your world won’t be easier if I did not come back.',
    'Baby, we must be a perfect match, because you’re in all my plans.',
    'I’m a paleontologist. I dig.',
    'Ouch! my tooth hurts because you’re so sweet.',
    'Are you butt dialing? Because I swear that a** is calling me.',
    'Your body is a wonderland, and I want to be Alice.',
    'Is your name highway? because I wanna ride you all night long.',
    'Your body is 70 percent water… and I’m thirsty.',
    'I’ve got buns, do you have a hotdog?',
    'I was feeling a little off today, but you definitely turned me on.',
    'Is your name winter? Because you’ll be coming soon.',
    'I’m easy, but it looks like you’re hard.',
    'Do you like sales? because if you’re looking for an absolute bargain, clothing is 100% off at my place.',
    'Let’s both be naughty together and save Santa a trip.',
    'Hey! My name is Microsoft. Can I crash at your place tonight?',
    'Are you a Jedi? Because I swear my lightsaber felt a disturbance in the force.',
    'I’m cold but you’re hot! let’s cuddle.',
    'Do you like bacon? wanna strip?',
    'Are you a campfire? because you’re hot and I want more.',
    'I can read your mind. Yes, I will sleep with you.',
    'Let’s play Titanic. When I say “iceberg”, you go down.',
    'I’d say God bless you, but it looks like He already did.',
    'We’re a match! The next step is to pick a wedding date, right?',
    'Wait a second. I need to breathe. Being with you takes my breath away 58. Hey, please keep your distance. I might fall for you any time.',
    'You seem familiar. You look a lot like my future boyfriend/husband.',
    'Can I ask you for a favor? I lost my phone number, can I’ve yours?',
    'Are you a camera? Because every time I look at you, I smile.',
    'My doctor told me I’m missing vitamin U. can you help me.',
    'I swear someone stole the stars from the sky and put them in your eyes.',
    'Did your license get suspended for driving all these girls crazy?',
    'Something wrong with my eyes, I cannot separate them from you.',
    'Nice shirt! What’s it made of, boyfriend material?',
    'I thought Happiness starts with “H” but why does mine start with “U”.',
    'If you were words on a page, you’d be what they call fine print.',
    'If you were a fruit, you’d be a fine-apple.',
    'I’m not a photographer, but I can picture us together.',
    'Excuse me, is your name Earl Grey? Because you look like a hot tea!',
    'I Want Someone To Look At Me The Way I Look At Chocolate Cake.',
    'I swear someone stole the stars from the sky and put them in your eyes.',
    'Hello, I’m A Thief, And I’m Here To Steal Your Heart.',
    'I think I could fall madly in bed with you.',
    'Don’t you just hate it when people try to use pick-up lines on you?',
    'Life without you is like a broken pencil. pointless!',
    'Are you a dictionary? Cause you’re adding meaning to my life.',
    'Do You Have A Name Or Can I Call You Mine?',
    'Your Lips Look Lonely Would They Like To Meet Mine?',
    'If beauty was a grain of sand, you’d be a thousand beaches.',
    'I’m no organ donor but I’d be happy to give you my heart.',
    'I couldn’t help but notice that you look a lot like my next girlfriend.',
    'Something must be wrong with my eyes because i can’t take them off you.',
    'Can you give me directions to your heart? because I’ve seemed to have lost in your eyes.',
    'Is there an airport nearby or is it my heart taking off?',
    'Can you take me to the doctor? I just broke my leg falling for you.',
    'Did your license get suspended for driving all these guys crazy?',
    'Are you french? Because Eiffel for you.',
    'If you were a transformer, you’d be Optimus Fine.',
    'Hey, you’re pretty and I’m cute. Together we’d be pretty cute.',
    'Have you been to the doctor lately? Cause I think you’re lacking some vitamin me.',
    'You are astoundingly dashing, but I can tell that’s the least interesting thing about you. I’d love to know more.',
    'If I had a nickel for every time I saw someone as beautiful as you, I’d still only have five cents.',
    'I was wondering if you had an extra heart because mine was just stolen.',
    'I’m blinded by your beauty so I need your name and phone number for insurance reasons.',
    'My name’s Microsoft, can i crash at your place tonight?',
    'When I look at you I feel like I’m a pirate and just found my buried treasure.',
    'My mom told me life was like a deck of cards. So, you must be the queen of hearts.',
    'If you were an item on the McDonald’s menu you would be a McHottie.',
    'Know what’s on the menu? Me ‘n’ u.',
  ],
};

export default FORGIRLS;
