const FORMEN = {
  name: 'Pickup lines for Men',
  title: 'Top Tinder & Bumble Pick up lines for Men',
  description:
    '<div><div>A good Tinder or Bumble ice breaker usually takes form in an open-ended question or joke that can easily lead into a fun conversation starter. It takes the awkwardness out of meeting people through a dating app and sets you up for success in the Bumble- or Tinder-verse!</div><br/><div>Need some inspiration for the next time you go swiping through dating apps? Take a peek at our favorite Tinder and Bumble pick-up lines, try out a few of your favorites, and see where things go!</div></div>',
  content: [
    'I usually go for 8’s but I guess I’ll settle for a 10.',
    'Forget hydrogen. You should be the number one element!',
    'Are you a bank loan? Because you have my interest.',
    'Are you a Middle Eastern dictator? Because you’re causing a political uprising in my pants!',
    'Are you the SAT? Cause I’d do you for 3 hours and 45 minutes, with a ten minute break in the middle for snacks.',
    'Are you the square root of 1? Because you seriously can’t be real!',
    'Can you stop staring at my profile and message me already? I don’t bite unless you ask.',
    'Damn, you have a dog! Does that mean I’ll never win the “best ever cuddler” title?',
    'Damn, you’re a knockout. Was your father a boxer, or did you just get lucky with the gene pool? ???? I bet you a cocktail your personality is even better than your looks too! ? ',
    'Did it hurt when you fell from heaven?',
    'Did you have lucky charms for breakfast? Because you look magically delicious!',
    'Do you believe in love at first sight, or should we match again?',
    'Do you believe in love at first swipe?',
    'Do you have a personality as intriguing as your eyes?',
    'Do you know the best thing about kisses? If you don’t like them, you can always return them.',
    'Do you like sleeping? Me too, we should do it together some time.',
    'I’d say you’re the bomb, but that could turn into lethal conversation…',
    'Hey gorgeous, will you be my Tinderella?',
    'I don’t flirt but I do have a habit of being extra nice to people who are extra attractive.',
    'If a thousand painters worked for a thousand years, they could not create a work of art as beautiful as you.',
    'If beauty were time, you’d be eternity.',
    'If I were to ask you out on a date, would your answer be the same as the answer to this question?',
    'If we were at home, cuddling on a rainy Sunday morning, what would we have for breakfast? a) American pancakes b) French crèpes c) waffles d) omelette e) "something else?"',
    'If you look that good in clothes, you must look even better out of them.',
    'If you were a triangle you’d be acute one.',
    'If you’re as good at cuddling as you’re good looking, I’m signing myself up on the waitlist for a date. ?',
    'I’m sure you get this all the time but you look like a mix between Fergie and Gandhi.',
    'I’m accepting applications if you want to apply, requirements include your phone number.',
    'I’m new in town. Could you give me directions to your apartment?',
    'Is your name Earl Grey? Because you look like a hot-tea!',
    'I seem to have lost my phone number. Can I have yours?',
    'I value my breath so I’d appreciate if you’d stop taking it away.',
    'Maybe you can help me. I forgot the password to my account, and when I hit ‘password hint,’ it keeps telling me ‘Jessica’s phone number.',
    'My mom told me not to talk to strangers online, but I’ll make an exception for you.',
    'My nickname at school was “the truth” girls just couldn’t handle me, what was yours?',
    'On a scale from 1 to 10, you’re a 9 and I’m the 1 you need.',
    'Since distance equals velocity times time, let’s let velocity and time approach infinity, because I want to go all the way with you.',
    'So, are you the kind I’d find climbing mountains and acing the diamond slopes, or chilling on the beach with a glass of wine?',
    'Sorry it took me so long to message you, I was at Whole Foods trying to figure out what you like for breakfast.',
    'Sorry, the position for Spanish teacher has been filled. What I’m looking for at the moment is a bedroom acrobatic teacher.',
    'Tell me, what can I say to impress you?',
    'They say Tinder is a numbers game… so can I get your number?',
    'This is so us. Me doing all the talking. You sitting there looking all cute.',
    'We matched! Does that mean you’re coming over to my place tonight, or should we meet and establish we aren’t serial killers or living with our parents first?',
    'When I was younger my fairy godmother said I can have a long penis or a long memory, I can’t remember my response.',
    'When our friends ask us how we met, what are we going to tell them?',
    'What’s a smart, attractive, young… man like me doing without your number?',
    'You look like you have great energy, I’m curious, where do you get it from? Yoga? Sports? Dance?',
    'You must be a small amount of red phosphorus and I must be a tiny wooden stick… Because we’re a match.',
    'You sound busy…any chance of adding me to your to-do list?',
    'You’re going to have to delete tinder, you’re making the other girls look bad.',
    'You’re seriously cute, but here’s the deal-breaker: do you, or do you not eat marmite?',
    'You’re so beautiful you just made me forget my pickup line.',
    'You’ve got the best smile on tinder. I bet you use Crest.',
    'All your pics came through at a 45-degree angle. Guess you’re acute-y.',
    'Are you a carbon sample? Because I want to date you.',
    'Are you a gardener? I like your tulips.',
    'Are you Australian? Because you meet all of my koala-fications.',
    'Are you French? Because Eiffel for you.',
    'Are you from space? Because you’re out of this world good-looking.',
    'Are you made of copper and tellurium? Because you’re CuTe',
    'Are you the COVID-19 vaccine? Because I would never turn you down.',
    'Are you my appendix? Because this feeling in my stomach makes me want to take you out.',
    'Dinner first, or can we go straight for dessert?',
    'Do you play soccer? You look like a keeper.',
    'Are you made of copper and tellurium? Because you’re CuTe.',
    'Do you like Mexican food? Cause I want to wrap you and make you my Baeritto.',
    'Do you mind if I walk you home? My mother always told me to follow my dreams.',
    'Do you ever wear fishnets? Because you’re a real catch.',
    'Can I have your picture so I can show Santa what I want for Christmas?',
    'Hi I’m doing a survey of which pickup lines guys think is the worst.',
    'Hi, I’m Mr. Right. Someone said you were looking for me?',
    'I bet I know when your birthday is. October 10. Because you’re a 10/10.',
    'Forget hydrogen. You should be the number one element!',
    'Excuse me, do you have a band-aid? Cause I scraped my knee falling for you.',
    'Don’t tell me your name. I’ve decided to just call you mine.',
    'Hey, I’m writing an article on the finer things in life and I was hoping I could interview you.',
    'I can’t believe we’ve known each other for a minute and still haven’t exchanged numbers.',
    'I hope your day has been as beautiful as you are.',
    'I don’t normally contact people on this, but I find you very intriguing.',
    'I think my phone’s busted. It keeps telling me it doesn’t have your number.',
    'I thought happiness started with an “h,” but I guess it actually starts with “u.”',
    'I’d say you’re as beautiful as a Greek goddess, but from what I can remember from history class, they were all pretty crazy.',
    'I would absolutely love to swap bodily fluids with you.',
    'I woke up thinking today was just another boring Monday, and then I saw your photo on my app.',
    'I’d tell you you’re cute, but someone else probably did that already, so you describe yourself in three emojis instead!',
    'I’m already picturing you naked. So what can I do to impress you so much I actually get to see you naked?',
    'I’m lost right now. Could you give me directions to your heart?',
    'I’m researching important dates in history, do you want to be mine?',
    'If God made anything more beautiful than you, I’m sure he’d keep it for himself.',
    'If I could rearrange the alphabet, I’d put U and I together.',
    'If you were a fruit, you’d be a fineapple.',
    'If you were a vegetable you’d be a cute-cumber.',
    'Life without you would be like a broken pencil… pointless',
    'My love for you is like copied assignment, I just can’t explain it.',
    'My love for you is like diarrhea, I just can’t hold it in.',
    'My mom thinks I’m gay, can you help me prove her wrong?',
    'Nice hair, wanna mess it up?',
    'What’s a perfect gentleman like myself doing without your phone number?',
    'You don’t know how many times I’ve had to swipe left to find you.',
    'You don’t need keys to drive me crazy.',
    'This time next year let’s be laughing together.',
    'That’s a nice shirt. Can I try it on after we have sex?',
    'Send me your favorite GIF so I get to know you better?',
    'Two truths and a lie! Go!',
    'What do you call a string of people lifting a mozzarella cheese? A cheesy pick-up line.',
    'Well, here I am. What are your other two wishes?',
    'What’s a good girl/guy like you doing on a naughty mind like mine?',
    'On a scale of one to the United States of America, how free are you for drinks this evening?',
    'Pick a historical era, and I’ll try to come up with a pick-up line related to that era.',
    'You look like trouble. I like it.',
    'You look so familiar… didn’t we take a class together? I could’ve sworn we had chemistry.',
    'You’re so gorgeous that you made me forget my good pick-up line.',
    'Your profile made me stop in my tracks.',
    'What’s the cheesiest pick up line you know? Hit me.',
    'What’s a perfect gentleman like me doing without your phone number?',
    'You sound busy but is there any chance of adding me to your to-do list?',
    'I’m new in town. Could you give me directions to your apartment?',
    'Are you a bank loan? Because you have my interest.',
    ' Are you from space? Because you’re out of this world good-looking.',
    'Roses are red, violets are blue, how did I get so lucky to match with you?',
    'Just wanted to let you know, you have some cute on your face.',
    'Are you my laptop? Because you’re really hot and I’m concerned.',
    'Are your parents bakers? They sure made a cutie pie.',
    'You’re seriously hot. And I’m seriously happy we matched.',
    'Do you have an Instagram? My mom always told me to follow my dreams.',
    'Did you fall in a pile of sugar? You’re looking super sweet.',
    'On a scale of one to the United States of America, how free are you for drinks this evening?',
    'Titanic. That’s my icebreaker. What’s up?',
    'Did you do something to my eyes? Because I can’t take them off you.',
    'Waffles or pancakes? I need to know what you prefer for breakfast.',
    'Your eyes are really beautiful, and I just had to tell you.',
    ' I almost gave up on Bumble, but then I saw your profile.',
    'Should we mix things up and get dessert before dinner?',
    'Hey, you’re beautiful. Can I tell you that again next Saturday over dinner?',
    'Kiss me if I’m wrong, but dinosaurs still exist, right?',
    'Hey, my name’s Microsoft. Can I crash at your place tonight?',
    'Is there an airport nearby or is it my heart taking off?',
    'Are you a meme? Because I’d like to show you to my friends and then hope they like you as much as I do.',
  ],
};

export default FORMEN;
